baseURL: "https://andreanovoa.github.io/" 
title: Andrea Nóvoa
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        # - name: Books
        #   url: books/
        #   weight: 5 
        - name: CV
          url: cv/
          weight: 1
        - name: Publications
          url: papers/
          weight: 2
        # - name: Publications
        #   url: publications/
          # weight: 3
        # - name: Data
        #   url: data/
        #   weight: 4 
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 6

params:
    description: "This website hosts Andrea Nóvoa's research papers, course materials, data, curriculum vitae, and contact information."
    author: Andrea Nóvoa
    defaultTheme: dark
    defaultColor: teal
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","data","courses"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Andrea Nóvoa
          subtitle: "Assistant Professor in Data Assimilation"
          subtitleInst: "Aeronautics Department | Imperial College London"
          subsubtitle: "Eric & Wendy Schmidt AI in Science Fellow"
          subsubtitleInst: "I-X Institute | Imperial College London"
          imageUrl: "headshot_wb.jpg"
          imageWidth: 160
          imageHeight: 160
          icon: "favicon-32x32.png"
          buttons:
            - name: About
              url: cv/
            - name: Publications
              url: papers/
            - name: Talks
              url: talks/

    socialIcons:
        - name: Email
          url: mailto:a[dot]novoa[at]imperial.ac.uk
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=X0TjtAgAAAAJ&hl=en
        - name: OrcID
          url: https://orcid.org/0000-0003-0597-8326
        - name: GitHub
          url: https://github.com/andreanovoa
        - name: Linkedin
          url: https://www.linkedin.com/in/andreanovoamartinez/
        
    
    assets:
        disableScrollBarStyle: true
        disableFeatherIcons: false
    enableFontAwesome: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Andrea Nóvoa"
      icon: "favicon-32x32.png"
      size:  16

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: monokai 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
