baseURL: "https://andreanovoa.github.io/andreanovoa-website/" 
title: Andrea Nóvoa
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        # - name: Books
        #   url: books/
        #   weight: 5 
        - name: CV
          url: cv/
          weight: 1
        - name: Papers
          url: papers/
          weight: 2
        # - name: Courses
        #   url: courses/
        #   weight: 3
        # - name: Data
        #   url: data/
        #   weight: 4 
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 6

params:
    description: "This website hosts Andrea Nóvoa's research papers, course materials, data, curriculum vitae, and contact information."
    author: Andrea Nóvoa
    # googleAnalyticsID: "G-XXXXX"
    # DateFormat: "1 June 2025"
    defaultTheme: dark
    defaultColor: teal
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","data","courses"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Andrea Nóvoa
          subtitle: "Research Fellow in Scientific Machine Learning"
          subsubtitle: "Aeronautics depatment, Imperial College London"
          imageUrl: "headshot_wb.jpg"
          imageWidth: 160
          imageHeight: 160
          icon: "favicon-32x32.png"
          buttons:
            - name: CV
              url: cv/
            - name: Publications
              url: papers/

    socialIcons:
        - name: Email
          url: mailto:a[dot]novoa[at]imperial.ac.uk
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=X0TjtAgAAAAJ&hl=en
        - name: OrcID
          url: https://orcid.org/my-orcid?orcid=0000-0003-0597-8326
        - name: GitHub
          url: https://github.com/andreanovoa
        - name: Linkedin
          url: https://www.linkedin.com/in/andreanovoamartinez/
        
    
    assets:
        disableScrollBarStyle: false
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Andrea Nóvoa"
      icon: "favicon-32x32.png"
      size:  16

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: monokai 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2